### ISSUE TITLE
做出回答！

### ISSUE THREAD

**Issue by LarryCC34** [jnz-jahangir/ZhangEmpire#3]
为祖国严惩领海的入侵，做最优质的战士。我们会打这个仗。金杰的去世，让我们更加团结一致！我们西方国家的朋友们，要对可耻的公然刺杀金杰，做出回答！今天，我们为被害的金杰哀悼；明天，我们就要让凶手付出代价！今天，我们为被害的金杰哀悼。明天，我们就要让凶手付出代价！中国不会允许，对我国领土领海的入侵，或对政治的干涉！Our great nation, united at the same sides, so many of us brought together by a single loss, we become one. Our friends in the west, will answer to the allegation, the sin of complicity in the shameful assassination of Jin Jie. 我们伟大的国家，拒绝屈服，共同的损失，让我们更加，团结一致！我们西方国家的朋友们，要为可耻共谋刺杀金杰而做出回答！

**Comment by jnz-jahangir** [comment]
尽整**没用的**，写代码去
